# Generated by Django 4.1.3 on 2022-11-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
