# Generated by Django 4.1.3 on 2022-11-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_quote_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='price',
            new_name='compel_price',
        ),
    ]
