# Generated by Django 4.1.3 on 2022-11-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_rename_price_quote_compel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='brand',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
