# Generated by Django 4.1.3 on 2022-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_quote_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='compel_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
