# Generated by Django 4.1.3 on 2022-11-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_quote_compel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='compel_price',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
    ]
